### ISSUE TITLE
the best K does not get plotted in the map and admixture plot

### ISSUE THREAD

**Issue by botanicpanic1** [rpyron/delim-SOM#1]
Hi! I am trying to run your code on my data:

Genetic data: 4648 SNPs from 71 populations (I kept one individual per pop)
Phenotypic data: 17 scaled morphometric variables from 71 populations (mean values per pop)
Spatial data: scaled longitude, latitude, and elevation
Climatic data: 19 scaled climatic variables from WorldClim

So I ran the SuperSOMs and I get as K = 2 as the most supported.
![image](https://github.com/user-attachments/assets/2d6c9d0e-b13a-4159-927e-b7bc60262050)
However when producing the map with the pie charts, and the admixture bar plot, K = 7 is plotted. Whereas in the SOM grid I get K = 4 
![image](https://github.com/user-attachments/assets/c351c2df-1b9e-4923-8999-878c97fff74f)...

I tried to modify the kohonen_code but did not work. Am I doing something wrong?

Thank you in advance for your help!

**Comment by rpyron** [comment]
You have not done anything wrong. What's happening is that delim-SOM does not select a single value of K - it averages across the sampled values. So in this instance, K=2 is not the "best" supported, but is just more sampled than K=4, etc.

Values of K2-7 are being sampled by the learning algorithm, so this is reflected in the map and bar charts in proportion to how frequently they are sampled. For the clusters, it's just showing you the most recent sampled value, which happens to be K=4; they are not averaged across runs.

In the next update, I will provide the ability to select specific values of K, which should solve your immediate problem, as well as average across the cluster plots. You say that you only kept one individual per pop; if you have more total individuals, I would include all of them.
